theme: minima
title: ECE 4160 Fast Robots Lab Notebook
author: Rishi Kansara
email: rkk58@cornell.edu
description: Lab Notebook for Fast Robots
permalink: none
header_pages:
  - about-me.md
  - /ECE-4160/labs/lab9/writeup.md
  
